
# SEO settings
title: "Should I Use a Password Manager?"
title2: "" # default: ""
description: "Helping people understand when to use a password manager."
keywords: "password, manager, security"
url: https://lifemeetscode.github.io # site url
baseurl: "/thinkspace" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: https://github.com/lifemeetscode.com/siuapm
disqus_shortname: "hnbloggithub"
twitter_username: "HeiswayiNrird"
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Adam Kammeyer"
  job      : ""
  bio      : "Iâ€™m a husband, father, PHP developer, manager, avid comic book reader, and wishful cyclist."
  thumb    : /images/author.jpg
  email    : contact@lifemeetscode.com
  url      : https://lifemeetscode.com
  github   : https://github.com/adamkammeyer
  twitter  : https://twitter.com/adamkammeyer
  facebook : 
  linkedin : 

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@adamkammeyer"

#gems:
#  - bourbon
#  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
